#!/bin/bash

cpp="g++"
cppflags="-std=c++11"
declare -a sources

pro="${1##*/}"
pro="${pro%%.pro}"
currdir=`pwd`
dir="${1%%/*}"

while read line
do
    if [[ $line == "SOURCES += "* ]]
    then
        linesources=(${line##*+= })
	for source in ${linesources[@]}
	do
		sources+=("$dir/$source")
	done
    fi
done < "$1"

echo "g++ ${cppflags} ${sources[@]} -o ${pro}"
#g++ ${cppflags} ${sources[@]} -o "${currdir}/result.bin"
