2:
	gcc lab2.c -o bin2

3:
	gcc lab3.c -o bin3

8:
	gcc lab8.c -o bin8

9:
	gcc lab9.c -o bin9

10:
	gcc lab10.c -o bin10

16:
	gcc lab16.c -o bin16

21:
	gcc lab21.c -o bin21

25:
	gcc lab25.c -o bin25

all:
	2
	3
	8
	9
	10
	16
	21
	25
